name: Lab CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Set working directory
      working-directory: ./e2e-screenshot-tests
      run: echo "Working directory set to /e2e-screenshot-tests"

    - name: Install dependencies
      working-directory: ./e2e-screenshot-tests
      run: npm install

    - name: Install Playwright browsers
      working-directory: ./e2e-screenshot-tests
      run: npx playwright install

    - name: Run tests
      working-directory: ./e2e-screenshot-tests
      run: npx playwright test --update-snapshots
